apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
  namespace: devops
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30128
  selector:
    app: nodejs-app
